name: Install
description: Install dependencies

runs:
    using: 'composite'
    steps:
        - name: Setup Node
          uses: actions/setup-node@v4
          with:
              registry-url: 'https://registry.npmjs.org/'
              node-version-file: '.nvmrc'
              cache: 'yarn'

        - name: Install dependencies
          shell: bash
          run: yarn install --immutable
